// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeroOnzeTour.DB;

namespace ZeroOnzeTourSite.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20231106235253_viagens")]
    partial class viagens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ZeroOnzeTour.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativo");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Texto");

                    b.HasKey("Id");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("ZeroOnzeTour.Models.ImagensTour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("Foto");

                    b.Property<int>("IdViagem")
                        .HasColumnType("int")
                        .HasColumnName("IdViagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<int?>("Ordem")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("Ordem");

                    b.Property<int>("TipoImagem")
                        .HasColumnType("int")
                        .HasColumnName("TipoImagem");

                    b.HasKey("Id");

                    b.ToTable("ImagensTour");
                });

            modelBuilder.Entity("ZeroOnzeTour.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativo");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .HasColumnType("text")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ZeroOnzeTour.Models.ViagemTour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativo");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cidade");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Data");

                    b.Property<string>("DataViagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DataViagem");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<string>("DescricaoRoteiro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DescricaoRoteiro");

                    b.Property<string>("Destaque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Destaque");

                    b.Property<string>("FraseDestaque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FraseDestaque");

                    b.Property<string>("FraseFinal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FraseFinal");

                    b.Property<string>("Incluso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Incluso");

                    b.Property<string>("NaoIncluso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NaoIncluso");

                    b.Property<string>("ObsInvestimento")
                        .HasColumnType("text")
                        .HasColumnName("ObsInvestimento");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("Ordem");

                    b.Property<string>("Pais")
                        .HasColumnType("text")
                        .HasColumnName("Pais");

                    b.Property<string>("SubTitulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SubTitulo");

                    b.Property<string>("Tutilo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Tutilo");

                    b.Property<string>("Valor")
                        .HasColumnType("text")
                        .HasColumnName("Valor");

                    b.Property<string>("ValorPrincipal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ValorPrincipal");

                    b.HasKey("Id");

                    b.ToTable("ViagemTour");
                });
#pragma warning restore 612, 618
        }
    }
}
